# Generated by Django 2.0.5 on 2019-11-11 05:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('Interest_category', models.CharField(max_length=100, primary_key='TRUE', serialize=False)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interest',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_id', models.CharField(default='DEFAULT VALUE', max_length=20)),
                ('Profile_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='ReadLater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Profile')),
            ],
            options={
                'verbose_name': 'ReadLater',
                'verbose_name_plural': 'ReadLater',
            },
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Profile')),
            ],
            options={
                'verbose_name': 'Saved',
                'verbose_name_plural': 'Saved',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('p_description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('Profile_name', models.ForeignKey(default='True', on_delete=django.db.models.deletion.CASCADE, related_name='Story', to='myapp.Profile')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Story',
            },
        ),
        migrations.AddField(
            model_name='interest',
            name='Profile_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='myapp.Profile'),
        ),
    ]
